# Generated by Django 3.0.5 on 2020-04-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0)),
                ('account_name', models.CharField(max_length=200)),
                ('account_password', models.CharField(max_length=200)),
                ('state', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('account_type', models.IntegerField(default=1)),
                ('account_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=100.0)),
                ('current_users', models.IntegerField(default=0)),
                ('his_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=1.0, max_digits=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('order_type', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=100.0)),
                ('history', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
