# Generated by Django 3.0.5 on 2020-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200411_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
